# Book settings
title: Applied Machine Learning and Data Analysis
author: Morten Hjorth-Jensen
logo: 'images/Picture.png'

latex:
  latex_documents:
    targetname: LectureNotes.tex

repository:
   url    :  https://github.com/CompPhysics/MachineLearning/tree/master/doc/src/LectureNotes
html:
  use_repository_button: true

# LaTeX-specific settings
latex:
  latex_engine              : pdflatex
  